name: Static Analysis
on: [pull_request]

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Psalm
              uses: docker://jakzal/phpqa:latest
              with:
                  args: psalm --output-format=github
