name: Unit Tests
on: [pull_request]

jobs:
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Phpunit
              uses: docker://jakzal/phpqa:latest
              with:
                  args: phpunit --testdox
